codecov:
  disable_default_path_fixes: yes

fixes:
  - "/home/runner/work/py_grama/py_grama/::" #Path fixing

ignore:
  - "/home/runner/work/py_grama/py_grama/tests"
  - "*/**/tests/**/*"
  - "test_*.py"
  - "test_autoplot.py"
